---
title: "BCB546_FinalGroupProject_Keller"
author: "Alex Keller"
date: "2023-04-17"
output: html_document
---

## Environment Setup

```{r, environment setup}
library(microseq)
library(seqinr)
library(dplyr)

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("DESeq2")

library(DESeq2)
```

Here is the whole workflow. I forgot to add the time points for the DESeq so I need to go back and do that.

```{r, workflow}
GSE114695_Gene <- `GSE114695_Gene_FC_P.val_FPKM.txt`
GSE114695_miRNA <- `GSE114695_miR_FC_P.val_RPM.txt`

#making a matrix - there are 18 total samples
coldata4 <- matrix(c(1:36), ncol = 2, byrow = TRUE)

# the condition is the genotype, so that is what we will want in the DeSeq object.
colnames(coldata4) = c('sample','condition')

# make it a dataframe for easier management. 
coldata4 <- as.data.frame(coldata4)

# assigning the rownames for coldata - they should all match the column names in countdata. 
rownames(coldata4) <- c("MI_Sham_1d.1_Read_Count", "MI_Sham_1d.3_Read_Count", "MI_Sham_1d.5_Read_Count",
                        "MI_Sham_1w.1_Read_Count", "MI_Sham_1w.3_Read_Count","MI_Sham_1w.5_Read_Count",
                        "MI_Sham_8w.1_Read_Count", "MI_Sham_8w.3_Read_Count", "MI_Sham_8w.5_Read_Count",
                        "MI_1d.2_Read_Count", "MI_1d.4_Read_Count", "MI_1d.9_Read_Count","MI_1w.2_Read_Count",
                        "MI_1w.6_Read_Count", "MI_1w.10_Read_Count", "MI_8w.2_Read_Count","MI_8w.4_Read_Count",
                        "MI_8w.7_Read_Count")

# adding in the genotypes - what the sample ID's correspond to.
coldata4$sample <- c('Sham_Day1', 'Sham_Day1','Sham_Day1','Sham_week1','Sham_week1','Sham_week1','Sham_week8',
                     'Sham_week8','Sham_week8', 'MI_Day1','MI_Day1','MI_Day1','MI_week1','MI_week1','MI_week1',
                     'MI_week8','MI_week8','MI_week8')

# adding the biological replicate labels so we can group them later in the analysis: 
coldata4$condition <- c('wildtype','wildtype','wildtype','wildtype','wildtype','wildtype','wildtype','wildtype',
                        'wildtype','myocardial_infraction','myocardial_infraction','myocardial_infraction',
                        'myocardial_infraction','myocardial_infraction','myocardial_infraction','myocardial_infraction',
                        'myocardial_infraction','myocardial_infraction')



# Making the DESeq object. 

# make genotype data a factor

coldata4$sample <- factor(coldata4$sample)
  
coldata4$sample <- factor(coldata4$sample)
coldata4$condition <- factor(coldata4$condition)

onlycountdata4 <- GSE114695_miRNA[c(74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91)]

onlycountdata4 <- onlycountdata4 %>% relocate("MI_Sham_1w.1_Read_Count","MI_Sham_1w.3_Read_Count","MI_Sham_1w.5_Read_Count",
                            .after = "MI_Sham_1d.5_Read_Count" )
onlycountdata4 <- onlycountdata4 %>% relocate("MI_Sham_8w.1_Read_Count", "MI_Sham_8w.3_Read_Count","MI_Sham_8w.5_Read_Count",
                                              .after = "MI_Sham_1w.5_Read_Count" )


# check that the order of column data (onlycountdata4) is consistent with the order of row data (coldata4). DeSeq2 will not match these up for you and the analysis will be incorrect. 
rownames(coldata4)
colnames(onlycountdata4) #samples order is consistent. 
all(rownames(coldata4) %in% colnames(onlycountdata4)) # making sure that all samples in coldata4 are in countdata4 and vise versa. 
all(rownames(coldata4) == colnames(onlycountdata4)) # rows and columns completely match. 


# making the DESeq object. 
dds4 <- DESeqDataSetFromMatrix(countData = onlycountdata4,
                              colData = coldata4,
                              design = ~condition)
#check DESeq object
dds4

# Pre-filtering low-expression miRNAs. Here, we are removing any count lower than 10, and keeping those in dds4 that are greater or equal to 10. 
keep <- rowSums(counts(dds4)) >= 10 
dds4 <- dds4[keep]


dds4$condition <- factor(dds4$condition, levels = c("myocardial_infraction","wildtype"))
dds4$condition <- relevel(dds4$condition, ref = "wildtype")

# DGE Analysis

dds4 <- DESeq(dds4)


# MI vs. Wildtype

res4 <- results(dds4, contrast=c('condition','wildtype', 'myocardial_infraction'))

# Applying False Discovery Rate. 
res4$p_val_fdr <- p.adjust(res$pvalue, method = "fdr")

# make a tibble
res4_tibble <- res4 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

# get rid of FDR adjusted p-values below .05: 
pfdr_cutoff <- 0.05
res4_tibble <- dplyr::filter(res4_tibble, p_val_fdr < pfdr_cutoff) %>%
  dplyr::arrange(p_val_fdr)
res4_tibble
write.csv(as.data.frame(res4_tibble), 
          file="MI_wildtype_results.csv")
```

## Redo for adding the times

```{r}
library(microseq)
library(seqinr)
library(dplyr)
library(DESeq2)

BiocManager::install("DESeq2")

library(DESeq2)

#making a matrix - there are 18 total samples
coldata_time <- matrix(c(1:54), ncol = 3, byrow = TRUE)

# the condition is the genotype, so that is what we will want in the DeSeq object.
colnames(coldata_time) = c('sample','condition','treatment')

# make it a dataframe for easier management. 
coldata_time <- as.data.frame(coldata_time)

# assigning the rownames for coldata - they should all match the column names in countdata. 
rownames(coldata_time) <- c("MI_Sham_1d.1_Read_Count", "MI_Sham_1d.3_Read_Count", "MI_Sham_1d.5_Read_Count",
                        "MI_Sham_1w.1_Read_Count", "MI_Sham_1w.3_Read_Count","MI_Sham_1w.5_Read_Count",
                        "MI_Sham_8w.1_Read_Count", "MI_Sham_8w.3_Read_Count", "MI_Sham_8w.5_Read_Count",
                        "MI_1d.2_Read_Count", "MI_1d.4_Read_Count", "MI_1d.9_Read_Count","MI_1w.2_Read_Count",
                        "MI_1w.6_Read_Count", "MI_1w.10_Read_Count", "MI_8w.2_Read_Count","MI_8w.4_Read_Count",
                        "MI_8w.7_Read_Count")

# adding in the genotypes - what the sample ID's correspond to.
coldata_time$sample <- c('Sham_Day1', 'Sham_Day1','Sham_Day1','Sham_week1','Sham_week1','Sham_week1','Sham_week8',
                     'Sham_week8','Sham_week8', 'MI_Day1','MI_Day1','MI_Day1','MI_week1','MI_week1','MI_week1',
                     'MI_week8','MI_week8','MI_week8')

# adding the biological replicate labels so we can group them later in the analysis: 
coldata_time$condition <- c('wildtype','wildtype','wildtype','wildtype','wildtype','wildtype','wildtype','wildtype',
                        'wildtype','myocardial_infraction','myocardial_infraction','myocardial_infraction',
                        'myocardial_infraction','myocardial_infraction','myocardial_infraction','myocardial_infraction',
                        'myocardial_infraction','myocardial_infraction')
coldata_time$treatment <- c('D1','D1','D1','W1','W1','W1','W8','W8','W8','D1','D1','D1','W1','W1','W1','W8','W8','W8')

# Making the DESeq object. 

# make genotype data a factor

coldata_time$treatment <- factor(coldata_time$treatment)
coldata_time$sample <- factor(coldata_time$sample)
coldata_time$condition <- factor(coldata_time$condition)

onlycountdata_time <- GSE114695_miRNA[c(74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91)]

onlycountdata_time <- onlycountdata_time %>% relocate("MI_Sham_1w.1_Read_Count","MI_Sham_1w.3_Read_Count","MI_Sham_1w.5_Read_Count",
                                              .after = "MI_Sham_1d.5_Read_Count" )
onlycountdata_time <- onlycountdata_time %>% relocate("MI_Sham_8w.1_Read_Count", "MI_Sham_8w.3_Read_Count","MI_Sham_8w.5_Read_Count",
                                              .after = "MI_Sham_1w.5_Read_Count" )
# check that the order of column data (onlycountdata4) is consistent with the order of row data (coldata4). DeSeq2 will not match these up for you and the analysis will be incorrect. 
rownames(coldata_time)
colnames(onlycountdata_time) #samples order is consistent. 
all(rownames(coldata_time) %in% colnames(onlycountdata_time)) # making sure that all samples in coldata4 are in countdata4 and vise versa. 
all(rownames(coldata_time) == colnames(onlycountdata_time)) # rows and columns completely match. 


# making the DESeq object. 
dds_time <- DESeqDataSetFromMatrix(countData = onlycountdata_time,
                               colData = coldata_time,
                               design = ~condition + treatment)
#check DESeq object
dds_time

# Pre-filtering low-expression miRNAs. Here, we are removing any count lower than 10, and keeping those in dds4 that are greater or equal to 10. 
keep <- rowSums(counts(dds_time)) >= 10 
dds4 <- dds_time[keep]


dds_time$condition <- factor(dds_time$condition, levels = c("myocardial_infraction","wildtype"))
dds_time$condition <- relevel(dds_time$condition, ref = "wildtype")
dds_time$treatment <- factor(dds_time$treatment, levels = c("D1", "W1", "W8"))

# DGE Analysis

dds_time <- DESeq(dds_time)


# D1 vs. W1 vs. W8

res_W1_vs_D1 <- results(dds_time, contrast=c("treatment","W1","D1"))
res_W8_vs_W1 <- results(dds_time, contrast=c("treatment","W8", "W1"))
res_D1_vs_W8 <- results(dds_time, contrast=c("treatment","D1", "W8"))

# Applying False Discovery Rate. 

res_W1_vs_D1$p_val_fdr <- p.adjust(res_W1_vs_D1$pvalue, method = "fdr")
res_W8_vs_W1$p_val_fdr <- p.adjust(res_W8_vs_W1$pvalue, method = "fdr")
res_D1_vs_W8$p_val_fdr <- p.adjust(res_D1_vs_W8$pvalue, method = "fdr")


# make a tibble
res_W1_vs_D1_tibble <- res_W1_vs_D1 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

res_W8_vs_W1_tibble <- res_W8_vs_W1 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

res_D1_vs_W8_tibble <- res_D1_vs_W8 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

# get rid of FDR adjusted p-values below .05: 
pfdr_cutoff <- 0.05
res_W1_vs_D1_tibble <- dplyr::filter(res_W1_vs_D1_tibble, p_val_fdr < pfdr_cutoff) %>%
  dplyr::arrange(p_val_fdr)
res_W1_vs_D1_tibble
write.csv(as.data.frame(res_W1_vs_D1_tibble), 
          file="W1_D1_results.csv")

pfdr_cutoff <- 0.05
res_W8_vs_W1_tibble <- dplyr::filter(res_W8_vs_W1_tibble, p_val_fdr < pfdr_cutoff) %>%
  dplyr::arrange(p_val_fdr)
res_W8_vs_W1_tibble
write.csv(as.data.frame(res_W8_vs_W1_tibble), 
          file="W8_W1_results.csv")

pfdr_cutoff <- 0.05
res_D1_vs_W8_tibble <- dplyr::filter(res_D1_vs_W8_tibble, p_val_fdr < pfdr_cutoff) %>%
  dplyr::arrange(p_val_fdr)
res_D1_vs_W8_tibble
write.csv(as.data.frame(res_D1_vs_W8_tibble), 
          file="D1_W8_results.csv")
```

## Code for all my Plots

```{r}
library(ggplot2)

#plot for D1 vs W8
ggplot(data = ggplotdf_D1_W8, aes(x=gene, y=fc, fill= fc)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("D1 vs W8")

ggplotdf_D1_W8 <- data.frame(gene = c("mmu-let-7i-5p", "mmu-miR-130a-3p", "mmu-miR-135a-5p", "mmu-148a-3p", "mmu-204-5p",
                               "mmu-miR-298-5p", "mmu-miR-30b-5p","mmu-miR-31-5p"), fc = c(-0.4756020, NaN, NaN, NaN, NaN, NaN, NaN, -1.92626))

#plots for W1 vs D1
ggplotdf_W1_D1 <- data.frame(gene = c("mmu-let-7i-5p", "mmu-miR-130a-3p", "mmu-miR-135a-5p", "mmu-148a-3p", "mmu-204-5p",
                                      "mmu-miR-298-5p", "mmu-miR-30b-5p","mmu-miR-31-5p"), fc = c(0.5958208, NaN, -1.489534, 1.30003, -1.035255, 1.428421, -0.694786, 1.527595))

ggplot(data = ggplotdf_W1_D1, aes(x=gene, y=fc, fill= fc)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("D1 vs W1")

#plot for W8 vs W1
ggplotdf_W8_W1 <- data.frame(gene = c("mmu-let-7i-5p", "mmu-miR-130a-3p", "mmu-miR-135a-5p", "mmu-148a-3p", "mmu-204-5p",
                                      "mmu-miR-298-5p", "mmu-miR-30b-5p","mmu-miR-31-5p"), fc = c(NaN, -0.7983188, 0.9715679, -0.8469518, NaN, -1.1040549, 0.4537448, NaN))

ggplot(data = ggplotdf_W8_W1, aes(x=gene, y=fc, fill= fc)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("W8 vs W1")

#plot for MI vs WT
ggplotdf_MI_WT <- data.frame(gene = c("mmu-let-7i-5p", "mmu-miR-130a-3p", "mmu-miR-135a-5p", "mmu-148a-3p", "mmu-204-5p",
                                      "mmu-miR-298-5p", "mmu-miR-30b-5p","mmu-miR-31-5p"), fc = c(-1.1215772, NaN, 2.015116, -1.170852, 0.9702756, -2.4449216, 1.3427150, -2.388818))

ggplot(data = ggplotdf_MI_WT, aes(x=gene, y=fc, fill= fc)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("MI vs WT")
```
